
import React from 'react';
import { AppItem, NavTab, ScheduledTask } from './types';
import * as LucideIcons from 'lucide-react';
import { 
  MessageSquare, 
  Bot, 
  GitBranch, 
  Search, 
  FileText, 
  Scissors, 
  Code, 
  Database, 
  BookOpen, 
  LayoutGrid,
  Wrench,
  Cloud,
  Cpu,
  Clock,
  Zap,
  TrendingUp,
  Briefcase,
  Layers,
  Box,
  Image as ImageIcon,
  Mail,
  MapPin,
  Shield,
  Mic,
  Search as SearchIcon,
  Activity,
  AlertTriangle,
  Folder,
  CloudSun,
  ClipboardList,
  Book,
  Bell,
  Heart,
  Settings,
  Users
} from 'lucide-react';

export const NAV_TABS: NavTab[] = [
  { id: 'app-dev', label: '应用开发' },
  { id: 'tools', label: '工具拓展' },
  { id: 'mcp', label: 'MCP服务' },
  { id: 'model', label: '模型服务' },
  { id: 'tasks', label: '定时任务' },
];

export const APP_TYPES: string[] = ['全部', '对话应用', '智能体应用', '工作流应用', '定制应用', '内置应用'];

export const SYSTEM_ICONS = [
  { name: 'MessageSquare', bgColor: 'bg-blue-600' },
  { name: 'TrendingUp', bgColor: 'bg-cyan-500' },
  { name: 'Briefcase', bgColor: 'bg-green-500' },
  { name: 'Layers', bgColor: 'bg-indigo-600' },
  { name: 'Box', bgColor: 'bg-blue-400' },
  { name: 'Zap', bgColor: 'bg-orange-500' },
  { name: 'Database', bgColor: 'bg-blue-700' },
  { name: 'Users', bgColor: 'bg-blue-600' },
  { name: 'Scissors', bgColor: 'bg-green-600' },
  { name: 'Activity', bgColor: 'bg-orange-500' },
  { name: 'BookOpen', bgColor: 'bg-sky-500' },
  { name: 'Bot', bgColor: 'bg-cyan-500' },
  { name: 'Layers', bgColor: 'bg-indigo-500' },
  { name: 'ClipboardList', bgColor: 'bg-blue-500' },
  { name: 'Box', bgColor: 'bg-blue-600' },
  { name: 'ImageIcon', bgColor: 'bg-orange-500' },
  { name: 'Mail', bgColor: 'bg-blue-500' },
  { name: 'MapPin', bgColor: 'bg-green-500' },
  { name: 'Shield', bgColor: 'bg-blue-600' },
  { name: 'Mic', bgColor: 'bg-cyan-500' },
  { name: 'SearchIcon', bgColor: 'bg-orange-500' },
  { name: 'Activity', bgColor: 'bg-cyan-400' },
  { name: 'AlertTriangle', bgColor: 'bg-orange-500' },
  { name: 'Folder', bgColor: 'bg-cyan-500' },
  { name: 'CloudSun', bgColor: 'bg-green-500' },
  { name: 'ClipboardList', bgColor: 'bg-orange-500' },
  { name: 'Book', bgColor: 'bg-green-600' },
  { name: 'Bell', bgColor: 'bg-cyan-500' },
  { name: 'Heart', bgColor: 'bg-blue-600' },
  { name: 'Settings', bgColor: 'bg-blue-500' },
  { name: 'LayoutGrid', bgColor: 'bg-green-500' },
  { name: 'Users', bgColor: 'bg-cyan-500' },
];

export const MOCK_APPS: AppItem[] = [
  {
    id: '1',
    name: '图谱问答',
    type: '对话应用',
    typeLabel: '对话助手',
    description: '基于知识图谱的智能问答助手，支持复杂逻辑推理。',
    icon: 'MessageSquare',
    iconType: 'icon',
    tags: ['对话助手', '知识库'],
    iconBgColor: 'bg-blue-600',
  },
  {
    id: '2',
    name: '对话助手（普通）',
    type: '对话应用',
    typeLabel: '对话助手',
    description: '通用的对话式AI助手，适用于日常咨询。',
    icon: 'MessageSquare',
    iconType: 'icon',
    tags: ['通用'],
    iconBgColor: 'bg-emerald-500',
  },
  {
    id: '3',
    name: '公众号文章撰写',
    type: '智能体应用',
    typeLabel: '智能体',
    description: '专注于生成高质量公众号文章的智能代理。',
    icon: 'Bot',
    iconType: 'icon',
    tags: ['写作', '媒体'],
    iconBgColor: 'bg-purple-600',
  },
  {
    id: '4',
    name: '网络搜索工具',
    type: '工具拓展',
    typeLabel: '对话助手',
    description: '用于检索网络资源，获取实时信息。',
    icon: 'Search',
    iconType: 'icon',
    tags: ['工具'],
    iconBgColor: 'bg-orange-500',
  },
];

export const MOCK_TASKS: ScheduledTask[] = [
  {
    id: '1',
    name: '测试1',
    description: '测试',
    app_id: '74e59d11-690d-41f7-9c85-b5998105ef76',
    app_name: '测试',
    appType: 'internal',
    api_endpoint: '/console/api/app_expand/74e59d11-690',
    request_body: { query: "" },
    method: 'POST',
    status: 'active',
    schedule_type: 'date',
    schedule_expression: '2026-02-05 14:10:17',
    created_at: '2026-02-05 14:10:29',
    updated_at: '2026-02-05 14:10:29',
    last_executed_at: '2026-02-05 14:10:29',
  },
  {
    id: '2',
    name: '测试定时任务',
    description: '讲一个小故事',
    app_id: 'story-teller-id',
    app_name: '对话助手（普通）',
    appType: 'internal',
    api_endpoint: '/console/api/app_expand/story-teller',
    request_body: { topic: "adventure" },
    method: 'POST',
    status: 'inactive',
    schedule_type: 'date',
    schedule_expression: '2026-02-02 14:14:00',
    created_at: '2026-02-02 14:07:50',
    updated_at: '2026-02-02 14:07:50',
    last_executed_at: null,
  },
  {
    id: '3',
    name: '任务名称：',
    description: '任务名称：',
    app_id: 'agent-test-id',
    app_name: '智能体测试',
    appType: 'internal',
    api_endpoint: '/console/api/agent/test',
    request_body: {},
    method: 'POST',
    status: 'active',
    schedule_type: 'interval',
    schedule_expression: '{"weeks":0,"days":1,"hours":0,"minutes":0,"seconds":0}',
    created_at: '2026-02-02 10:44:58',
    updated_at: '2026-02-02 10:44:58',
    last_executed_at: '2026-02-02 10:44:58',
  },
  {
    id: '4',
    name: '任务名',
    description: '任务名',
    app_id: 'agent-test-id',
    app_name: '智能体测试',
    appType: 'external',
    api_endpoint: 'https://api.example.com/webhook',
    request_body: { event: "ping" },
    method: 'POST',
    status: 'inactive',
    schedule_type: 'interval',
    schedule_expression: '{"weeks":0,"days":0,"hours":2,"minutes":0,"seconds":0}',
    created_at: '2026-02-02 10:41:09',
    updated_at: '2026-02-02 10:41:09',
    last_executed_at: null,
  },
  {
    id: '5',
    name: '676767',
    description: '新建任务',
    app_id: 'agent-test-id',
    app_name: '智能体测试',
    appType: 'internal',
    api_endpoint: '/console/api/agent/676767',
    request_body: {},
    method: 'POST',
    status: 'active',
    schedule_type: 'interval',
    schedule_expression: '{"days":1}',
    created_at: '2026-02-02 10:36:13',
    updated_at: '2026-02-02 10:36:13',
    last_executed_at: '2026-02-02 10:36:13',
  },
  {
    id: '6',
    name: '测试面板',
    description: '讲一个小故事',
    app_id: 'story-id',
    app_name: '对话助手（普通）',
    appType: 'internal',
    api_endpoint: '/console/api/app/story',
    request_body: {},
    method: 'POST',
    status: 'active',
    schedule_type: 'interval',
    schedule_expression: '{"weeks":null,"days":null,"hours":null,"minutes":1,"seconds":null}',
    created_at: '2026-02-02 10:33:03',
    updated_at: '2026-02-02 10:33:03',
    last_executed_at: '2026-02-02 10:33:03',
  },
  {
    id: '7',
    name: '可视面板',
    description: '111111111111',
    app_id: 'visual-panel-id',
    app_name: '智能体测试',
    appType: 'internal',
    api_endpoint: '/console/api/visual/panel',
    request_body: { id: "111" },
    method: 'POST',
    status: 'active',
    schedule_type: 'interval',
    schedule_expression: '{"weeks":null,"days":null,"hours":1,"minutes":null,"seconds":2}',
    created_at: '2026-02-02 09:42:55',
    updated_at: '2026-02-02 09:42:55',
    last_executed_at: '2026-02-02 09:42:55',
  },
];

export const getIcon = (name: string, className?: string) => {
  const IconComponent = (LucideIcons as any)[name];
  if (IconComponent) {
    return <IconComponent className={className} />;
  }
  return <Bot className={className} />;
};
